USE [master]
GO
/****** Object:  Database [PayrollDB]    Script Date: 5/8/2026 10:24:52 AM ******/
CREATE DATABASE [PayrollDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PayrollDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\PayrollDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PayrollDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\PayrollDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PayrollDB] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PayrollDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PayrollDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PayrollDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PayrollDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PayrollDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PayrollDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [PayrollDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PayrollDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PayrollDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PayrollDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PayrollDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PayrollDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PayrollDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PayrollDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PayrollDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PayrollDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PayrollDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PayrollDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PayrollDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PayrollDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PayrollDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PayrollDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PayrollDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PayrollDB] SET RECOVERY FULL 
GO
ALTER DATABASE [PayrollDB] SET  MULTI_USER 
GO
ALTER DATABASE [PayrollDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PayrollDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PayrollDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PayrollDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PayrollDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PayrollDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PayrollDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [PayrollDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [PayrollDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PayrollDB]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 5/8/2026 10:24:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[HourlyRate] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HoursWorked]    Script Date: 5/8/2026 10:24:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HoursWorked](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeID] [int] NULL,
	[HoursWorked] [decimal](5, 2) NULL,
	[WorkDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PayrollDB] SET  READ_WRITE 
GO
